# syntax=docker/dockerfile:experimental

ARG PLANETILER_TAG=0.7.0

FROM ghcr.io/cmahnke/map-tools/planetiler:${PLANETILER_TAG}

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-tools

ENV BUILD_DEPS="wget" \
    BUILD_DIR=/tmp/build \
    PLANETILER_DATA_DIR=/usr/share/planetiler \
    PLANETILER_DIR=/opt/planetiler

RUN --mount=target=/mnt/build-context \
    apk --update upgrade && \
    apk add --no-cache $BUILD_DEPS && \
    mkdir -p $BUILD_DIR $PLANETILER_DIR $PLANETILER_DATA_DIR && \
    cp /mnt/build-context/docker/planetiler/scripts/* $BUILD_DIR && \
    cd $BUILD_DIR && \
    ./get-data.sh && \
## Cleanup
    cd / && \
    apk del $BUILD_DEPS && \
    rm -rf /var/cache/apk/* $BUILD_DIR

WORKDIR $BUILD_DIR
