# syntax=docker/dockerfile:experimental

ARG PLANETILER_TAG=0.7.0

FROM ghcr.io/cmahnke/map-tools/planetiler:${PLANETILER_TAG}

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-tools

ENV BUILD_DEPS="wget" \
    PLANETILER_DATA_DIR=/usr/share/planetiler

RUN apk --update upgrade && \
    apk add --no-cache $RUN_DEPS && \
    mkdir -p $PLANETILER_DATA_DIR/data/sources/  && \
    cd $PLANETILER_DIR_DATA/data/sources/ && \
    wget https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip && \
    wget https://dev.maptiler.download/geodata/omt/lake_centerline.shp.zip && \
    wget https://dev.maptiler.download/geodata/omt/natural_earth_vector.sqlite.zip && \
## Cleanup
    cd / && \
    apk del $BUILD_DEPS && \
    rm -rf /var/cache/apk/*

WORKDIR $BUILD_DIR
