# syntax=docker/dockerfile:experimental

FROM ubuntu:24.04

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-tools

ENV BUILD_DEPS="wget git make autoconf automake llvm g++ zlib1g-dev build-essential" \
    RUN_DEPS="zlib1g" \
    OSMCTOOLS_GIT_REPO="https://gitlab.com/osm-c-tools/osmctools.git" \
    OSMCTOOLS_GIT_TAG="master" \
    BUILD_DIR=/tmp/build

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y $BUILD_DEPS $RUN_DEPS && \
    mkdir -p $BUILD_DIR $DATA_DIR && \
    cd $BUILD_DIR && \
## OSM C Tools
    git clone --depth 1 --branch $OSMCTOOLS_GIT_TAG $OSMCTOOLS_GIT_REPO && \
    cd osmctools && \
    autoreconf --install && \
    ./configure --prefix=/opt/osmctools && \
    make && make install && \
    cd .. && \
# Create links
    for filepath in /opt/**/bin/* ; do \
      filename=$(basename $filepath) ; \
      if ! test -e /usr/local/bin/$filename ; then \
        ln -s $filepath /usr/local/bin/$filename ; \
      fi ; \
    done && \
# Cleanup
    rm -rf $BUILD_DIR && \
    apt-get remove -y $BUILD_DEPS && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/apt/lists/*
