name: Publish Central Europe extended Data

permissions:
  packages: write
  contents: write

on:
  workflow_run:
    workflows: ["Publish Data"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron:  '30 10 * * 1'

jobs:
  build_central-europe-ext:
    name: Push central-europe-ext Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' '^postgresql-.*' '^gfortran-.*' '^cmake-.*' '^aspnetcore-.*' '^libmono-.*' '^mono-.*' '^ruby.*' '^r-.*' azure-cli google-cloud-sdk google-chrome-stable firefox powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/ /opt/hostedtoolcache /opt/microsoft /usr/local/aws-*
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          build-args: |
            COVERAGE=central-europe-ext.json
            MAX_ZOOM=13
          tags: |
            ghcr.io/cmahnke/map-action/data/central-europe-ext:latest
