name: Publish Data
on:
#  workflow_run:
#    workflows: ["Publish Ubuntu Docker images"]
#    branches: [main]
#    types:
#      - completed
  push:
    branches:
      - main
  schedule:
    - cron:  '30 4 * * 1'

jobs:
  build_central-europe:
    name: Push central-europe Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          tags: |
            ghcr.io/cmahnke/map-action/data/central-europe:latest

  build_central-europe-ext:
    name: Push central-europe-ext Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          build-args: |
            COVERAGE=central-europe-ext.json
          tags: |
            ghcr.io/cmahnke/map-action/data/central-europe-ext:latest
