name: Publish Data
on:
#  workflow_run:
#    workflows: ["Publish Ubuntu Docker images"]
#    branches: [main]
#    types:
#      - completed
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * 1'

# TODO: Also remove  Java

jobs:
  build_central-europe:
    name: Push central-europe Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y '^gfortran-.*'
          sudo apt-get remove -y '^cmake-.*'
          sudo dpkg --remove azure-cli google-cloud-sdk google-chrome-stable firefox powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          build-args: |
            MAX_ZOOM=13
          tags: |
            ghcr.io/cmahnke/map-action/data/central-europe:latest

  build_central-europe-ext:
    name: Push central-europe-ext Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y '^gfortran-.*'
          sudo apt-get remove -y '^cmake-.*'
          sudo dpkg --remove  azure-cli google-cloud-sdk google-chrome-stable firefox powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          build-args: |
            COVERAGE=central-europe-ext.json
            MAX_ZOOM=13
          tags: |
            ghcr.io/cmahnke/map-action/data/central-europe-ext:latest

  build_goettingen:
    name: Push goettingen Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y '^gfortran-.*'
          sudo apt-get remove -y '^cmake-.*'
          sudo dpkg --remove  azure-cli google-cloud-sdk google-chrome-stable firefox powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          build-args: |
            COVERAGE=goettingen.json
            MAX_ZOOM=14
            EXCLUDE_LAYERS=""
            FILTER_BUILDINGS=false
          tags: |
            ghcr.io/cmahnke/map-action/data/goettingen:latest
