name: Publish Ubuntu Docker images

permissions:
  packages: write
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Docker images"]
    branches: [main]
    types:
      - completed

jobs:

  build_osmium:
    name: Push osmium Ubuntu Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/osmium/Dockerfile.ubuntu-22.04
          tags: |
            ghcr.io/cmahnke/map-tools/osmium:ubuntu-22.04

  build_tilemaker:
    name: Push tilemaker Ubuntu Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/tilemaker/Dockerfile.ubuntu-22.04
          tags: |
            ghcr.io/cmahnke/map-tools/tilemaker:ubuntu-22.04

  build_osmctools:
    name: Push tilemaker Ubuntu Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/osmctools/Dockerfile.ubuntu-22.04
          tags: |
            ghcr.io/cmahnke/map-tools/osmctools:ubuntu-22.04

  test:
    name: Test Ubuntu Docker images for linking errors
    runs-on: ubuntu-latest
    needs: [build_osmium, build_tilemaker]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y liblua5.1-0 zlib1g liblz4-1 libsqlite3-0 libbz2-1.0 libboost-program-options1.74.0 libboost-filesystem1.74.0 libboost-iostreams1.74.0 libprotobuf23 expat libgdal30 liblz4-1 libgeos-c1v5

      - name: Extract
        run: |
          sudo chmod +w /opt
          docker pull ghcr.io/cmahnke/map-tools/osmium:ubuntu-22.04
          docker create --name osmium ghcr.io/cmahnke/map-tools/osmium:ubuntu-22.04
          docker cp osmium:/opt/osmium /opt/osmium
          docker rm -f osmium
          docker rmi ghcr.io/cmahnke/map-tools/osmium:ubuntu-22.04

          docker pull ghcr.io/cmahnke/map-tools/tilemaker:ubuntu-22.04
          docker create --name tilemaker ghcr.io/cmahnke/map-tools/tilemaker:ubuntu-22.04
          docker cp tilemaker:/opt/tilemaker /opt/tilemaker
          docker rm -f tilemaker
          docker rmi ghcr.io/cmahnke/map-tools/tilemaker:ubuntu-22.04

          docker pull ghcr.io/cmahnke/map-tools/osmctools:ubuntu-22.04
          docker create --name osmctools ghcr.io/cmahnke/map-tools/tilemaker:ubuntu-22.04
          docker cp osmctools:/opt/osmctools /opt/osmctools
          docker rm -f osmctools
          docker rmi ghcr.io/cmahnke/map-tools/osmctools:ubuntu-22.04

      - name: Check ldd
        run: |
          ls -al /opt
          for filepath in /opt/{tilemaker,osmium}/bin/*
          do
            echo "Checking $filepath"
            ldd $filepath
          done
